apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
  namespace: mysql-ns
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: flyway
        image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag }}"
        command: ["flyway", "migrate"]
        env:
        - name: FLYWAY_URL
          value: jdbc:mysql://cafee-mysql:3306/coffee_shop?allowPublicKeyRetrieval=true&useSSL=false
        - name: FLYWAY_USER
          value: barista
        - name: FLYWAY_PASSWORD
          value: espresso1
      restartPolicy: OnFailure
